config/routes.rb
Spree::Core::Engine.routes.prepend do
  namespace :admin do
    resources :boleto_docs
  end
  resources :orders do
    resources :boleto_docs
  end
end

app/models/spree/boleto_doc.rb
module Spree
  class BoletoDoc < ActiveRecord::Base
    # status: issued, cancelled, paid
    serialize :payload
    has_one :payment, :as => :source
    belongs_to :order
    attr_accessor :vencimento_fixo

    validates :due_date, presence: true
    
    [:pending, :cancelled, :paid].each do |state|
      scope state, where("status = ?", state.to_s)
    end
    scope :active, where("status != ?", "cancelled")
    
    def process!(payment)
      order = payment.order
      prefs = Spree::Boleto::Configuration.preferences.dup
      banco = prefs.delete(:banco).classify      
      formato = prefs.delete(:formato)
      parcelas = prefs.delete(:parcelas)
      per_page = prefs.delete(:per_page)
      @boleto = "Brcobranca::Boleto::#{banco}".constantize.new(prefs)
      @boleto.sacado = order.name
      @boleto.valor = payment.amount
      @boleto.numero_documento = id
      @boleto.data_documento = Date.today
      @boleto.sacado_endereco = order.bill_address.full_address
      @boleto.sacado_documento = order.bill_address.document
      @boleto.vencimento_fixo = due_date
      self.payload = @boleto
      self.document_number = @boleto.numero_documento
      save
      payment.pend
    end
    
    def actions
      %w{capture void}
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      ['processing', 'checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def capture(payment)
      update_attribute(:status, "paid")
      payment.complete
      true
    end

    def void(payment)
      update_attribute(:status, "cancelled")
      payment.void
      true
    end
  end
end

app/controllers/spree/admin/boleto_docs_controller.rb
module Spree
  module Admin
    class BoletoDocsController < Spree::Admin::BaseController
      respond_to :html
      
      def index
        params[:q] ||= {}
        params[:q][:meta_sort] ||= 'due_date.asc'

        @search = Spree::BoletoDoc.ransack(params[:q])

        if !params[:q][:due_date_gt].blank?
          params[:q][:due_date_gt] = Time.zone.parse(params[:q][:due_date_gt]).beginning_of_day rescue ""
        end

        if !params[:q][:due_date_lt].blank?
          params[:q][:due_date_lt] = Time.zone.parse(params[:q][:due_date_lt]).end_of_day rescue ""
        end

        @boleto_docs = Spree::BoletoDoc.ransack(params[:q]).result
          .joins(:order, :payment).includes([:order, :payment])
          .page(params[:page]).per(Spree::Boleto::Configuration[:per_page])
        respond_with(@boleto_docs)
      end
    end
  end
end

app/controllers/spree/boleto_docs_controller.rb
# encoding:utf-8
module Spree
  class BoletoDocsController < Spree::BaseController
    before_filter :check_authorization
    before_filter :load_order
    respond_to :html, :image, :pdf

    layout "spree/layouts/print_layout"
    
    def index
      @boletos = []
      @order.boleto_docs.pending.each do |boleto_doc|
        @boletos << boleto_doc.payload
      end
      respond_to do |format|
        format.html
        format.pdf do
          formato = "pdf"
          headers['Content-Type']= PaymentMethod::BoletoMethod::FORMATS[formato]
          send_data Brcobranca::Boleto::Base.lote(@boletos), :filename => "boletos_#{@order.number}.#{formato}", :disposition => "attachment", :type => PaymentMethod::BoletoMethod::FORMATS[formato]
        end
      end
    end
    
    def show
      @boleto_doc = @order.boleto_docs.find(params[:id])
      @boleto = @boleto_doc.payload
      respond_to do |format|
        format.html
        format.pdf do
          formato = "pdf"
          headers['Content-Type']= PaymentMethod::BoletoMethod::FORMATS[formato]
          send_data @boleto.to(formato), :filename => "boleto_#{@boleto_doc.order.number}_#{@boleto_doc.id}.#{formato}", :disposition => "attachment", :type => PaymentMethod::BoletoMethod::FORMATS[formato]
        end
        format.image do
          formato = "jpg"
          headers['Content-Type']= PaymentMethod::BoletoMethod::FORMATS[formato]
          send_data @boleto.to(formato), :filename => "boleto_#{@boleto_doc.order.number}_#{@boleto_doc.id}.#{formato}", :disposition => 'inline', :type => PaymentMethod::BoletoMethod::FORMATS[formato]
        end
      end
    end
    
    private 
    def check_authorization
      session[:access_token] ||= params[:token]
      order = current_order || Spree::Order.find_by_number(params[:order_id])

      if order
        authorize! :edit, order, session[:access_token]
      else
        authorize! :create, Spree::Order
      end
    end
    
    def load_order
      @order = Spree::Order.find_by_number(params[:order_id])
    end
  end
end

app/helpers/spree/boleto_docs_helper.rb
module Spree
  module BoletoDocsHelper
    def default_due_date
      date = Date.today + Spree::Boleto::Configuration.preferences[:dias_vencimento]
      l(date)
    end
  end
end

app/views/spree/admin/boleto_docs/_boleto_links.html.erb
<td>
	<p>
		individual =>
		impressao: <%= clippy order_boleto_doc_url(boleto_doc.order.number, boleto_doc, :auth_token => boleto_doc.order.user.authentication_token) %>
		pdf: <%= clippy order_boleto_doc_url(boleto_doc.order.number, boleto_doc, :auth_token => boleto_doc.order.user.authentication_token, :format => :pdf) %>
	</p>
	<p>
		pendentes =>
		impressao: <%= clippy order_boleto_docs_url(boleto_doc.order.number, :auth_token => boleto_doc.order.user.authentication_token) %>
		pdf: <%= clippy order_boleto_docs_url(boleto_doc.order.number, :auth_token => boleto_doc.order.user.authentication_token, :format => :pdf) %>
	</p>
</td>

app/views/spree/admin/boleto_docs/_tab.html.erb
<li <%== ' class="active"' if (defined? current and current == 'Boletos') %>>
  <%= link_to t(:boletos), admin_boleto_docs_url %>
</li>

app/views/spree/admin/boleto_docs/index.html.erb
<% content_for :sidebar do %>
  <div class="box" data-hook="admin_boletos_index_search">
    <h3><%= t(:search) %></h3>
    <%= search_form_for [:admin, @search] do |f| %>
      <%= label_tag nil, t(:date_range) %><br />
      <div class="date-range-filter">
        <div class="left sub-field">
          <%= f.text_field :due_date_gt, :class => 'datepicker' %><br />
          <%= label_tag nil, t(:start), :class => 'sub' %>
        </div>
        <div class="right sub-field">
          <%= f.text_field :due_date_lt, :class => 'datepicker' %><br />
          <%= label_tag nil, t(:stop), :class => 'sub' %>
        </div>
      </div>
      <p><%= label_tag nil, t(:status) %><br />
      <%= f.select :status_eq, [:pending, :paid, :cancelled].map {|s| [t("boleto.#{s}"), s]}, {:include_blank => true} %></p>
      <p>
        <%= label_tag nil, t(:boleto_number) %><br />
        <%= f.text_field :document_number_cont, :size => 25 %>
      </p>
      <p>
        <%= f.label :amount_gteq, t(:amount_gteq) %><br />
        <%= f.text_field :amount_gteq, :size => 15 %>
      </p>
      <p>
        <%= f.label :amount_lt, t(:amount_lt) %><br />
        <%= f.text_field :amount_lt, :size => 15 %>
      </p>
      <div data-hook="admin_boletos_index_search_buttons">
        <p><%= button t(:search) %></p>
      </div>
    <% end %>
  </div>
<% end %>


<h1><%= Spree::BoletoDoc.model_name.human(:count => 2) %></h1>

<table class="index" id="listing_boletos" data-hook>
  <thead>
    <tr data-hook="admin_boletos_index_headers">
      <% if @show_only_completed %>
        <th><%= sort_link @search, :paid_at, Spree::BoletoDoc.human_attribute_name(:paid_at) %></th>
      <% else %>
        <th><%= sort_link @search, :due_date,   		Spree::BoletoDoc.human_attribute_name(:due_date) %></th>
      <% end %>
      <th><%= sort_link @search, :document_number,	Spree::BoletoDoc.human_attribute_name(:document_number) %></th>
      <th><%= sort_link @search, :status,         	Spree::BoletoDoc.human_attribute_name(:status) %></th>
      <th><%= sort_link @search, :order_id,         t(:order) %></th>
      <th><%= sort_link @search, :amount,          	t(:amount) %></th>
			<th>link</th>
      <th data-hook="admin_boletos_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
		<% @boleto_docs.each do |boleto_doc| %>
		<% next if boleto_doc.order.blank? || boleto_doc.payment.blank? %>
			<tr data-hook="admin_boletos_index_rows">
			  <td><%= l (@show_only_completed ? boleto_doc.paid_at : boleto_doc.due_date).to_date rescue nil %></td>
			  <td><%= link_to boleto_doc.document_number, admin_order_payment_path(boleto_doc.order, boleto_doc.payment) %></td>
			  <td><%= t("boleto.#{boleto_doc.status}") %></td>
			  <td><%= link_to boleto_doc.order.number, admin_order_path(boleto_doc.order) %></td>
			  <td><%= number_to_currency boleto_doc.amount %></td>
				<%= render :partial => "boleto_links", :object => boleto_doc, :as => :boleto_doc %>
				<td class='actions' data-hook="admin_boletos_index_row_actions">
			    <% boleto_doc.payment.actions.each do |action| %>
			      <%= button_to t(action), fire_admin_order_payment_path(boleto_doc.order, boleto_doc.payment, :e => action), :method => :put %>
			    <% end %>
			  </td>
			</tr>
		<% end %>
  </tbody>
</table>
<%= paginate @boleto_docs %>